FROM ${IMAGE}

ADD https://github.com/itamae-kitchen/mitamae/releases/download/v${MITAMAE_VERSION}/mitamae-${MITAMAE_ARCH} /usr/local/bin/mitamae
RUN chmod +x /usr/local/bin/mitamae

COPY ./mitamae /usr/local/share/mitamae
RUN /usr/local/bin/mitamae local -y /usr/local/share/mitamae/node.yml /usr/local/share/mitamae/cookbooks/system/default.rb

WORKDIR /workspace

ENV LANG=C.UTF-8

USER ${USER}

RUN /usr/local/bin/mitamae local /usr/local/share/mitamae/cookbooks/user/default.rb
