x-app: &app_base
  build: .
  volumes:
    - ../redmine:/usr/src/redmine
    - ../plugins:/usr/src/redmine/plugins
    - bundle-data:/usr/local/bundle
  env_file:
    - ./.user.env
  environment:
    RAILS_ENV: ${RAILS_ENV:-development}
    WEBPACK_HOST: webpack
    WEBPACK_PORT: 3035

services:
  redmine:
    <<: *app_base
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - webpack
      - db
    ports:
      - 3000:3000
  webpack:
    <<: *app_base
    command: bash -c "rm -rf public/packs && yarn webpack serve"
    ports:
      - 3035:3035
  db:
    image: postgres:13.3
    env_file:
      - ./.dbpass.env
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  bundle-data:
  db-data:
