x-app: &app_base
  build: .
  volumes:
    - ../redmine:/usr/src/redmine
    - bundle-data:/usr/local/bundle
  environment:
    LOCAL_UID: ${LOCAL_UID}
    LOCAL_GID: ${LOCAL_GID}

services:
  redmine:
    <<: *app_base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - webpack
      - railsdb
    ports:
      - 3000:3000
  webpack:
    <<: *app_base
    command: bash -c "rm -rf public/packs && yarn webpack serve"
    ports:
      - 3035:3035
  railsdb:
    container_name: railsdb
    image: postgres:12.2
    environment:
      POSTGRES_DB: railsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-dev:/var/lib/postgresql/data
volumes:
  bundle-data:
  db-dev:
